### ISSUE TITLE
Bulma

### ISSUE THREAD

**Issue by phillygogo** [Janksturgh/Vue-Development-Skeleton#1]
why bulma? :P

**Comment by Janksturgh** [comment]
> why bulma? :P

Hi @phillygogo ! thanks for the question, well i wanted to implement a css and html framework that could get you off the ground quickly, i was thinking about implementing Bootstrap, but i want this to be as lightweight as possible so to implement bootstrap with all its javacript, css and html felt like overkill, i also looked at tailwind.css but that wasn't going to work either as that is just a utility based css framework and doesn't come with any html boilerplates, so that is why i ended up going with bulma

Thanks for the question, all the best!
